add_newline = false

[hostname]
ssh_only = false
format =  "@(bold blue)[$hostname](bold red) "

[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style)"
show_always = true

[character]
success_symbol = "[✓](bold white)" 
error_symbol = "[✗](bold red) "

[directory]
truncate_to_repo = false

[line_break]
# disabled = true
