inherits = "gruvbox_dark_hard"

# Remove bold modifiers
"constructor" = { fg = "purple1" }
"function" = { fg = "green1" }
"constant.builtin" = { fg = "purple1" }
"constant.character.escape" = { fg = "fg2" }

# Make selection not invert colors
"ui.selection" = { bg = "bg3" }
"ui.selection.primary" = { bg = "bg4" }

# Transparent background
"ui.background" = {}